cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"

brew "readline"
brew "xz"
brew "awscli"
brew "curl"
brew "docker"
brew "git"
brew "git-secrets"
brew "mas"
brew "nkf"
brew "tree"
brew "vim"
brew "zsh-completions"

cask "1password"
cask "blackhole"
cask "docker"
cask "font-hackgen"
cask "google-chrome"
cask "google-japanese-ime"
cask "slack"
cask "openinterminal-lite"
cask "visual-studio-code"
cask "xmind"
cask "warp"
cask "raycast"

mas "Slac", id: 803453959
mas "LadioCast", id: 411213048
